# Generated by Django 2.0.10 on 2019-02-10 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0002_auto_20190131_1904'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_share',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_u_ip', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='jb_num',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='share_address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user_share',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_share_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
