# Generated by Django 2.0.10 on 2019-02-10 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0003_auto_20190210_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_share',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='user_share',
        ),
    ]
