# Generated by Django 2.0.10 on 2019-02-10 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0004_auto_20190210_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_share',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_u_ip', models.CharField(max_length=200, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_share_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
