# Generated by Django 2.0.10 on 2019-02-12 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0006_lock_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hot_article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hot_article_id', to='mm.Article')),
            ],
        ),
    ]
